name: Mkdir Action
author: Alfi Maulana
description: Create a new directory
branding:
  icon: folder-plus
  color: white
inputs:
  name:
    description: Name of the directory to create
    required: true
runs:
  using: composite
  steps:
    - shell: bash
      run: mkdir ${{ inputs.name }}
