name: Action
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  test:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [windows, ubuntu, macos]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.0.0

      # Modify the following steps for testing your composite action.
      # Learn more: https://docs.github.com/en/actions/automating-builds-and-tests

      - name: Test directory should not exist
        shell: bash
        run: "! test -d dir"

      - name: Create test directory
        uses: ./
        with:
          name: dir

      - name: Test directory should exist
        shell: bash
        run: test -d dir
