name: build
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.0.0

      - name: Test directory should not exist
        run: "! test -d dir"

      - name: Create test directory
        uses: ./
        with:
          name: dir

      - name: Test directory should exist
        run: test -d dir
