name: Test
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  test-action:
    name: Test Action
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [windows, ubuntu, macos]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.5
        with:
          path: mkdir-action
          sparse-checkout: action.yml
          sparse-checkout-cone-mode: false

      # Modify the following steps for testing your composite action.
      # Learn more: https://docs.github.com/en/actions/automating-builds-and-tests

      - name: Directory Should Not Exist
        shell: bash
        run: "! test -d dir"

      - name: Create Directory
        uses: ./mkdir-action
        with:
          name: dir

      - name: Directory Should Exist
        shell: bash
        run: test -d dir
